travis:
  secure:
    BINSTAR_TOKEN: F1w5SG8hXi9DWa4bPcRZ0nmdY6BDEzacG10ev+u08Kb5gaKBbq8m7QekiOP5AsL5sosfZ+8dWSUtgzCJ7CKmw9TYbir/e4yGyR+v3WJI4fW1Yydlb4qKjFY/35lHkBHwm0sfULXPcbC0YlMCGaf2zFukLg5Mt+idEqQ0lBCGm7+uoT0a4hZa8kBzTQEyQe7uk29OyK9LKbVzdd5n3c/xVdZvk/k+aim4Qc1pQUrHV+sB0N3/cK30rOQ0feVrY7Mq47FUh90LaXGPXckmsv9p0FKpBERl4BJqI744hj3AYGu9QtOT2lO8EIG6eZKhrTP5+sY3I4CWeVpM9wxJRuAInRnbmBYtt+5Nou6QHqKFJY6LwsyE6K/lbWftsEWH5I4Wix3ugZXVXDvsv3n6fSG5kW7Uw8ZHGF0HW3i5NZD8eWEBp0qGpt5coqm3nMeEEsORmr6+YUxHsMMALY/862w1rxWCPo/Fwir8Qq/qohOnX5+iq9w6pU6WX8i3gOAkDMI37IbZd8BNs0yBe09AcEXIPPstvSYM3sqWbVXkXTMcnpfzOoPoH5Z1zx2FQunoGWwbhHqz+mO9DztOQaJhvPJSV0/QPAtBCc7cZEHBghFBPZ+kBaLXuEcl0qKWqjl8UTvEzgxkbHzCg9WW1zpE0+1hWoz/HyyFXPK4DsXdjoY7MCU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
